# Generated by Django 5.2 on 2025-04-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
