# Generated by Django 5.2 on 2025-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0002_remove_contact_first_name_remove_contact_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='vat_numer',
            new_name='vat_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_ext',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
