# Generated by Django 5.2 on 2025-04-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(default='IT', on_delete=django.db.models.deletion.CASCADE, to='contactsApp.country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactsApp.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactsApp.city'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactsApp.sede'),
        ),
    ]
