# Generated by Django 5.2 on 2025-04-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0003_contact_country_contact_region_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactsApp.country'),
        ),
    ]
